spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/nostr
    username: nostr
    password: nostr
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8008